name: Check formatting and linting using shfmt and shellcheck

on: [push, pull_request]

jobs:
  shfmt:
    name: Shfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shfmt

      - name: Style Check
        run: shfmt -d install.sh

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Lint
        run: shellcheck install.sh
