name: linting using shellcheck

on: [push, pull_request]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y fontconfig curl unzip
          sudo apt-get install -y shellcheck

      - name: Lint
        run: shellcheck install.sh
