name: lint using shellcheck

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  lint:
    name: start linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck

      - name: Lint install.sh
        run: shellcheck install.sh
