name: test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    name: start testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl fontconfig unzip

      - name: Test font installation via local install.sh
        run: |
          nerd_font_name="Hack" bash ./install.sh
